// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiefwqSwVe9Hgu_tkOqaZLASqwfaPzG8o',
    appId: '1:482236235557:web:7ac844db55fc0d01e764cc',
    messagingSenderId: '482236235557',
    projectId: 'trader-1111',
    authDomain: 'trader-1111.firebaseapp.com',
    storageBucket: 'trader-1111.appspot.com',
    measurementId: 'G-SGRY9NNB4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5AtyorvbFxjyW0qP2eEuI19ciPXyCpcI',
    appId: '1:482236235557:android:25f6c276b88cd549e764cc',
    messagingSenderId: '482236235557',
    projectId: 'trader-1111',
    storageBucket: 'trader-1111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0wb_R4yoCAZ2nxQIWojD_zPAfR6qrAIo',
    appId: '1:482236235557:ios:a2465e0de6baf264e764cc',
    messagingSenderId: '482236235557',
    projectId: 'trader-1111',
    storageBucket: 'trader-1111.appspot.com',
    iosClientId: '482236235557-9frv4c078k5apm1uf3araevua9q24k40.apps.googleusercontent.com',
    iosBundleId: 'com.companyname.packagename.trade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0wb_R4yoCAZ2nxQIWojD_zPAfR6qrAIo',
    appId: '1:482236235557:ios:a2465e0de6baf264e764cc',
    messagingSenderId: '482236235557',
    projectId: 'trader-1111',
    storageBucket: 'trader-1111.appspot.com',
    iosClientId: '482236235557-9frv4c078k5apm1uf3araevua9q24k40.apps.googleusercontent.com',
    iosBundleId: 'com.companyname.packagename.trade',
  );
}
