import 'package:cloud_firestore/cloud_firestore.dart';

const double customRadius = 14;

List countries = [
  "AR",
  "AT",
  "AU",
  "BD",
  "BE",
  "BO",
  "BR",
  "CA",
  "CL",
  "CN",
  "CR",
  "CU",
  "DE",
  "DK",
  "ES",
  "ET",
  "GB",
  "ID",
  "IN",
  "JO",
  "JP",
  "KH",
  "MX",
  "NG",
  "NL",
  "NZ",
  "PE",
  "PH",
  "PK",
  "TR",
  "US",
  "VN"
];

List cities = [
  {
    "country": "US",
    "cities": [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "District of Columbia",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
      "American Samoa",
      "Guam",
      "Northern Mariana Islands",
      "Puerto Rico",
      "United States Minor Outlying Islands",
      "Virgin Islands"
    ]
  },
  {
    "country": "CA",
    "cities": [
      "Alberta",
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Nova Scotia",
      "Nunavut",
      "Northwest Territories",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
      "Yukon"
    ]
  },
  {
    "country": "AU",
    "cities": [
      "Ashmore and Cartier Islands",
      "Australian Antarctic Territory",
      "Australian Capital Territory",
      "Christmas Island",
      "Cocos Islands",
      "Coral Sea Islands",
      "Heard Island and McDonald Islands",
      "Jervis Bay Territory",
      "New South Wales",
      "Norfolk Island",
      "Northern Territory",
      "Queensland",
      "South Australia",
      "Tasmania",
      "Victoria",
      "Western Australia"
    ]
  },
  {
    "country": "MX",
    "cities": [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Coahuila",
      "Colima",
      "Federal District",
      "Durango",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "Mexico",
      "Michoacán",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz",
      "Yucatán",
      "Zacatecas"
    ]
  },
  {
    "country": "CN",
    "cities": [
      "重庆",
      "黑龙江",
      "吉林",
      "海南",
      "北京",
      "辽宁",
      "内蒙古",
      "西藏",
      "青海",
      "宁夏",
      "新疆",
      "甘肃",
      "河北",
      "河南",
      "湖北",
      "湖南",
      "山东",
      "江苏",
      "安徽",
      "山西",
      "陕西",
      "四川",
      "云南",
      "贵州",
      "浙江",
      "福建",
      "广西",
      "上海",
      "天津",
      "香港",
      "澳门",
      "台湾",
      "江西",
      "广东"
    ]
  },
  {
    "country": "GB",
    "cities": [
      "Avon",
      "Bedfordshire",
      "Berkshire",
      "Borders",
      "Bristol",
      "Buckinghamshire",
      "Cambridgeshire",
      "Channel Islands",
      "Cheshire",
      "Cleveland",
      "Cornwall",
      "Cumbria",
      "Derbyshire",
      "Devon",
      "Dorset",
      "Durham",
      "East Riding of Yorkshire",
      "East Sussex",
      "Essex",
      "Gloucestershire",
      "Greater Manchester",
      "Hampshire",
      "Herefordshire",
      "Hertfordshire",
      "Humberside",
      "Isle of Man",
      "Isle of Wight",
      "Isles of Scilly",
      "Kent",
      "Lancashire",
      "Leicestershire",
      "Lincolnshire",
      "London",
      "Merseyside",
      "Middlesex",
      "Norfolk",
      "North Yorkshire",
      "Northamptonshire",
      "Northumberland",
      "Nottinghamshire",
      "Oxfordshire",
      "Rutland",
      "Shropshire",
      "Somerset",
      "South Yorkshire",
      "Staffordshire",
      "Suffolk",
      "Surrey",
      "Tyne and Wear",
      "Warwickshire",
      "West Midlands",
      "West Sussex",
      "West Yorkshire",
      "Wiltshire",
      "Worcestershire",
      "Antrim",
      "Down",
      "Fermanagh",
      "Londonderry",
      "Tyrone",
      "Aberdeen City",
      "Aberdeenshire",
      "Angus",
      "Argyll and Bute",
      "Armagh",
      "Carmarthenshire",
      "Clackmannan",
      "Dumfries and Galloway",
      "East Ayrshire",
      "East Dunbartonshire",
      "East Lothian",
      "East Renfrewshire",
      "Edinburgh City",
      "Falkirk",
      "Fife",
      "Glasgow",
      "Highland",
      "Inverclyde",
      "Midlothian",
      "Moray",
      "North Ayrshire",
      "North Lanarkshire",
      "Orkney",
      "Perthshire and Kinross",
      "Renfrewshire",
      "Roxburghshire",
      "Shetland",
      "South Ayrshire",
      "South Lanarkshire",
      "Stirling",
      "West Dunbartonshire",
      "West Lothian",
      "Western Isles",
      "Blaenau Gwent",
      "Bridgend",
      "Caerphilly",
      "Cardiff",
      "Ceredigion",
      "Conwy",
      "Denbighshire",
      "Flintshire",
      "Gwynedd",
      "Isle of Anglesey",
      "Merthyr Tydfil",
      "Monmouthshire",
      "Neath Port Talbot",
      "Newport",
      "Pembrokeshire",
      "Powys",
      "Rhondda Cynon Taff",
      "Swansea",
      "The Vale of Glamorgan",
      "Torfaen",
      "Wrexham"
    ]
  },
  {
    "country": "DE",
    "cities": [
      "Baden-Württemberg",
      "Bayern",
      "Berlin",
      "Brandenburg",
      "Bremen",
      "Hamburg",
      "Hessen",
      "Mecklenburg-Vorpommern",
      "Niedersachsen",
      "Nordrhein-Westfalen",
      "Rheinland-Pfalz",
      "Saarland",
      "Sachsen",
      "Sachsen-Anhalt",
      "Schleswig-Holstein",
      "Thüringen"
    ]
  },
  {
    "country": "NL",
    "cities": [
      "Drenthe",
      "Flevoland",
      "Friesland",
      "Gelderland",
      "Groningen",
      "Limburg",
      "Noord-Brabant",
      "Noord-Holland",
      "Overijssel",
      "Utrecht",
      "Zuid-Holland",
      "Zeeland"
    ]
  },
  {
    "country": "BE",
    "cities": [
      "Antwerpen",
      "Henegouwen",
      "Luik",
      "Limburg",
      "Luxemburg",
      "Namen",
      "Oost-Vlaanderen",
      "Vlaams-Brabant",
      "Waals-Brabant",
      "West-Vlaanderen"
    ]
  },
  {
    "country": "DK",
    "cities": [
      "Hovedstaden",
      "Midtjylland",
      "Nordjylland",
      "Sjælland",
      "Syddanmark"
    ]
  },
  {
    "country": "TR",
    "cities": [
      "Adana",
      "Adıyaman",
      "Afyonkarahisar",
      "Ağrı",
      "Amasya",
      "Ankara",
      "Antalya",
      "Artvin",
      "Aydın",
      "Balıkesir",
      "Bilecik",
      "Bingöl",
      "Bitlis",
      "Bolu",
      "Burdur",
      "Bursa",
      "Çanakkale",
      "Çankırı",
      "Çorum",
      "Denizli",
      "Diyarbakır",
      "Edirne",
      "Elazığ",
      "Erzincan",
      "Erzurum",
      "Eskişehir",
      "Gaziantep",
      "Giresun",
      "Gümüşhane",
      "Hakkâri",
      "Hatay",
      "Isparta",
      "Mersin",
      "Istanbul",
      "İzmir",
      "Kars",
      "Kastamonu",
      "Kayseri",
      "Kırklareli",
      "Kırşehir",
      "Kocaeli",
      "Konya",
      "Kütahya",
      "Malatya",
      "Manisa",
      "Kahramanmaraş",
      "Mardin",
      "Muğla",
      "Muş",
      "Nevşehir",
      "Niğde",
      "Ordu",
      "Rize",
      "Sakarya",
      "Samsun",
      "Siirt",
      "Sinop",
      "Sivas",
      "Tekirdağ",
      "Tokat",
      "Trabzon",
      "Tunceli",
      "Şanlıurfa",
      "Uşak",
      "Van",
      "Yozgat",
      "Zonguldak",
      "Aksaray",
      "Bayburt",
      "Karaman",
      "Kırıkkale",
      "Batman",
      "Şırnak",
      "Bartın",
      "Ardahan",
      "Iğdır",
      "Yalova",
      "Karabük",
      "Kilis",
      "Osmaniye",
      "Düzce"
    ]
  },
  {
    "country": "ID",
    "cities": [
      "Special Region of Aceh",
      "Bali",
      "Bangka–Belitung Islands",
      "Banten",
      "Bengkulu",
      "Central Java",
      "Central Kalimantan",
      "Central Sulawesi",
      "East Java",
      "East Kalimantan",
      "East Nusa Tenggara",
      "Gorontalo",
      "Jakarta Special Capital Region",
      "Jambi",
      "Lampung",
      "Maluku",
      "North Kalimantan",
      "North Maluku",
      "North Sulawesi",
      "North Sumatra",
      "Special Region of Papua",
      "Riau",
      "Riau Islands",
      "Southeast Sulawesi",
      "South Kalimantan",
      "South Sulawesi",
      "South Sumatra",
      "West Java",
      "West Kalimantan",
      "West Nusa Tenggara",
      "Special Region of West Papua",
      "West Sulawesi",
      "West Sumatra",
      "Special Region of Yogyakarta"
    ]
  },
  {
    "country": "JO",
    "cities": [
      "Irbid",
      "Ajloun",
      "Jerash",
      "Mafraq",
      "Balqa",
      "Amman",
      "Zarqa",
      "Madaba",
      "Karak",
      "Tafilah",
      "Ma'an",
      "Aqaba"
    ]
  },
  {
    "country": "IN",
    "cities": [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jammu and Kashmir",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Dadra and Nagar Haveli",
      "Daman and Diu",
      "Lakshadweep",
      "National Capital Territory of Delhi",
      "Puducherry"
    ]
  },
  {
    "country": "KH",
    "cities": [
      "ភ្នំពេញ",
      "បន្ទាយមានជ័យ",
      "បាត់ដំបង",
      "កំពង់ចាម",
      "កំពង់ឆ្នាំង",
      "កំពង់ស្ពឺ",
      "កំពង់ធំ",
      "កំពត",
      "កណ្តាល",
      "កោះកុង",
      "កែប",
      "ក្រចេះ",
      "មណ្ឌលគីរី",
      "ឧត្តរមានជ័យ",
      "បៃលិន",
      "ព្រះសីហនុ",
      "ព្រះវិហារ",
      "ពោធិ៍សាត់",
      "ព្រៃវែង",
      "រតនគីរី",
      "សៀមរាប",
      "ស្ទឹងត្រែង",
      "ស្វាយរៀង",
      "តាកែវ",
      "ត្បូងឃ្មុំ"
    ]
  },
  {
    "country": "ET",
    "cities": [
      "Addis Ababa",
      "Afar Region",
      "Amhara Region",
      "Benishangul-Gumuz",
      "Dire Dawa",
      "Gambela",
      "Harari",
      "Oromia",
      "Somali",
      "Southern Nations, Nationalities, and Peoples' Region",
      "Tigray Region"
    ]
  },
  {
    "country": "PE",
    "cities": [
      "Chachapoyas",
      "Bagua",
      "Bongará",
      "Condorcanqui",
      "Luya",
      "Rodríguez de Mendoza",
      "Utcubamba",
      "Huaraz",
      "Aija",
      "Antonio Raymondi",
      "Asunción",
      "Bolognesi",
      "Carhuaz",
      "Carlos Fermín Fitzcarrald",
      "Casma",
      "Corongo",
      "Huari",
      "Huarmey",
      "Huaylas",
      "Mariscal Luzuriaga",
      "Ocros",
      "Pallasca",
      "Pomabamba",
      "Recuay",
      "Santa",
      "Sihuas",
      "Yungay",
      "Abancay",
      "Andahuaylas",
      "Antabamba",
      "Aymaraes",
      "Cotabambas",
      "Chincheros",
      "Grau",
      "Arequipa",
      "Camaná",
      "Caravelí",
      "Castilla",
      "Caylloma",
      "Condesuyos",
      "Islay",
      "La Unión",
      "Huamanga",
      "Cangallo",
      "Huanca Sancos",
      "Huanta",
      "La Mar",
      "Lucanas",
      "Parinacochas",
      "Páucar del Sara Sara",
      "Sucre",
      "Víctor Fajardo",
      "Vilcas Huamán",
      "Cajamarca",
      "Cajabamba",
      "Celendín",
      "Chota",
      "Contumazá",
      "Cutervo",
      "Hualgayoc",
      "Jaén",
      "San Ignacio",
      "San Marcos",
      "San Miguel",
      "San Pablo",
      "Santa Cruz",
      "Callao",
      "Cusco",
      "Acomayo",
      "Anta",
      "Calca",
      "Canas",
      "Canchis",
      "Chumbivilcas",
      "Espinar",
      "La Convención",
      "Paruro",
      "Paucartambo",
      "Quispicanchi",
      "Urubamba",
      "Huancavelica",
      "Acobamba",
      "Angaraes",
      "Castrovirreyna",
      "Churcampa",
      "Huaytará",
      "Tayacaja",
      "Huánuco",
      "Ambo",
      "Dos de Mayo",
      "Huacaybamba",
      "Huamalíes",
      "Leoncio Prado",
      "Marañón",
      "Pachitea",
      "Puerto Inca",
      "Lauricocha",
      "Yarowilca",
      "Ica",
      "Chincha",
      "Nazca",
      "Palpa",
      "Pisco",
      "Huancayo",
      "Concepción",
      "Chanchamayo",
      "Jauja",
      "Junín",
      "Satipo",
      "Tarma",
      "Yauli",
      "Chupaca",
      "Trujillo",
      "Ascope",
      "Bolívar",
      "Chepén",
      "Julcán",
      "Otuzco",
      "Pacasmayo",
      "Pataz",
      "Sánchez Carrión",
      "Santiago de Chuco",
      "Gran Chimú",
      "Virú",
      "Chiclayo",
      "Ferreñafe",
      "Lambayeque",
      "Lima",
      "Huaura",
      "Barranca",
      "Cajatambo",
      "Canta",
      "Cañete",
      "Huaral",
      "Huarochirí",
      "Oyón",
      "Yauyos",
      "Maynas",
      "Alto Amazonas",
      "Loreto",
      "Mariscal Ramón Castilla",
      "Putumayo",
      "Requena",
      "Ucayali",
      "Datem del Marañón",
      "Tambopata",
      "Manú",
      "Tahuamanu",
      "Mariscal Nieto",
      "General Sánchez Cerro",
      "Ilo",
      "Pasco",
      "Daniel Alcídes Carrión",
      "Oxapampa",
      "Piura",
      "Ayabaca",
      "Huancabamba",
      "Morropón",
      "Paita",
      "Sullana",
      "Talara",
      "Sechura",
      "Puno",
      "Azángaro",
      "Carabaya",
      "Chucuito",
      "El Collao",
      "Huancané",
      "Lampa",
      "Melgar",
      "Moho",
      "San Antonio de Putina",
      "San Román",
      "Sandia",
      "Yunguyo",
      "Moyobamba",
      "Bellavista",
      "El Dorado",
      "Huallaga",
      "Lamas",
      "Mariscal Cáceres",
      "Picota",
      "Rioja",
      "San Martín",
      "Tocache",
      "Tacna",
      "Candarave",
      "Jorge Basadre",
      "Tarata",
      "Tumbes",
      "Contralmirante Villar",
      "Zarumilla",
      "Coronel Portillo",
      "Atalaya",
      "Padre Abad",
      "Purús"
    ]
  },
  {
    "country": "CU",
    "cities": [
      "Camagüey",
      "Ciego de Ávila",
      "Cienfuegos",
      "Havana",
      "Bayamo",
      "Guantánamo",
      "Holguín",
      "Nueva Gerona",
      "Artemisa",
      "Las Tunas",
      "Matanzas",
      "San José de las Lajas",
      "Pinar del Río",
      "Sancti Spíritus",
      "Santiago de Cuba",
      "Santa Clara"
    ]
  },
  {
    "country": "AR",
    "cities": [
      "Ciudad Autónoma de Buenos Aires",
      "Buenos Aires",
      "Catamarca",
      "Chaco",
      "Chubut",
      "Córdoba",
      "Corrientes",
      "Entre Ríos",
      "Formosa",
      "Jujuy",
      "La Pampa",
      "La Rioja",
      "Mendoza",
      "Misiones",
      "Neuquén",
      "Río Negro",
      "Salta",
      "San Juan",
      "San Luis",
      "Santa Cruz",
      "Santa Fe",
      "Santiago del Estero",
      "Tierra del Fuego, Antártida e Islas del Atlántico Sur",
      "Tucumán"
    ]
  },
  {
    "country": "CL",
    "cities": [
      "Arica",
      "Parinacota",
      "Iquique",
      "Tamarugal",
      "Antofagasta",
      "El Loa",
      "Tocopilla",
      "Copiapó",
      "Huasco",
      "Chañaral",
      "Elqui",
      "Limarí",
      "Choapa",
      "Isla de Pascua",
      "Los Andes",
      "Marga Marga",
      "Petorca",
      "Quillota",
      "San Antonio",
      "San Felipe de Aconcagua",
      "Valparaíso",
      "Cachapoal",
      "Colchagua",
      "Cardenal Caro",
      "Talca",
      "Linares",
      "Curicó",
      "Cauquenes",
      "Concepción",
      "Ñuble",
      "Biobío",
      "Arauco",
      "Cautin",
      "Malleco",
      "Valdivia",
      "Ranco",
      "Llanquihue",
      "Osorno",
      "Chiloe",
      "Palena",
      "Coihaique",
      "Aisén",
      "General Carrera",
      "Capitan Prat",
      "Magallanes",
      "Ultima Esperanza",
      "Tierra del Fuego",
      "Antártica Chilena",
      "Santiago",
      "Cordillera",
      "Maipo",
      "Talagante",
      "Melipilla",
      "Chacabuco"
    ]
  },
  {
    "country": "BO",
    "cities": [
      "Cercado",
      "Iténez",
      "José Ballivián",
      "Mamoré",
      "Marbán",
      "Moxos",
      "Vaca Díez",
      "Yacuma",
      "Azurduy",
      "Belisario Boeto",
      "Hernando Siles",
      "Jaime Zudáñez",
      "Luis Calvo",
      "Nor Cinti",
      "Oropeza",
      "Sud Cinti",
      "Tomina",
      "Yamparáez",
      "Arani",
      "Arque",
      "Ayopaya",
      "Capinota",
      "Carrasco",
      "Cercado",
      "Chapare",
      "Esteban Arce",
      "Germán Jordán",
      "Mizque",
      "Campero",
      "Punata",
      "Quillacollo",
      "Bolívar",
      "Tapacarí",
      "Tiraque",
      "Abel Iturralde",
      "Aroma",
      "Bautista Saavedra",
      "Caranavi",
      "Eliodoro Camacho",
      "Franz Tamayo",
      "Gualberto Villarroel",
      "Ingavi",
      "Inquisivi",
      "José Manuel Pando",
      "Larecaja",
      "Loayza",
      "Los Andes",
      "Manco Kapac",
      "Muñecas",
      "Nor Yungas",
      "Omasuyos",
      "Pacajes",
      "Murillo",
      "Sud Yungas",
      "Atahuallpa",
      "Carangas",
      "Cercado",
      "Eduardo Avaroa",
      "Ladislao Cabrera",
      "Litoral",
      "Nor Carangas",
      "Pantaléon Dalence",
      "Poopó",
      "Puerto de Mejillones",
      "Sajama",
      "San Pedro de Totora",
      "Saucarí",
      "Sebastián Pagador",
      "Sud Carangas",
      "Tomas Barrón",
      "Abuná",
      "Federico Román",
      "Madre de Dios",
      "Manuripi",
      "Nicolás Suárez",
      "Alonso de Ibáñez",
      "Antonio Quijarro",
      "Bernardino Bilbao",
      "Charcas",
      "Chayanta",
      "Cornelio Saavedra",
      "Daniel Campos",
      "Enrique Baldivieso",
      "José María Linares",
      "Modesto Omiste",
      "Nor Chichas",
      "Nor Lípez",
      "Rafael Bustillo",
      "Sur Chichas",
      "Sur Lípez",
      "Tomás Frías",
      "Andrés Ibáñez",
      "Ángel Sandoval",
      "Chiquitos",
      "Cordillera",
      "Florida",
      "Germán Busch",
      "Guarayos",
      "Ichilo",
      "Ignacio Warnes",
      "José Miguel de Velasco",
      "Manuel María Caballero",
      "Ñuflo de Chávez",
      "Obispo Santistevan",
      "Sara",
      "Vallegrande",
      "Aniceto Arce",
      "Burnet O'Connor",
      "Cercado",
      "Eustaquio Méndez",
      "Gran Chaco",
      "José María Avilés"
    ]
  },
  {
    "country": "ES",
    "cities": [
      "La Coruña",
      "Lugo",
      "Vizcaya",
      "Guipúzcoa",
      "Huesca",
      "Lérida",
      "Gerona",
      "Barcelona",
      "Tarragona",
      "Castellón",
      "Valencia",
      "Alicante",
      "Murcia",
      "Zaragoza",
      "Teruel",
      "Cuenca",
      "Albacete",
      "Almeria",
      "Granada",
      "Málaga",
      "Tenerife",
      "Cádiz",
      "Sevilla",
      "Huelva",
      "Las Palmas",
      "Madrid",
      "Badajoz",
      "Cáceres",
      "Toledo",
      "Ciudad Real",
      "Salamanca",
      "Córdoba",
      "Jaén",
      "Ávila",
      "Valladolid",
      "Zamora",
      "Álava",
      "Segovia",
      "Burgos",
      "Pontevedra",
      "León",
      "Orense",
      "Palencia",
      "La Rioja",
      "Soria",
      "Guadalajara"
    ]
  },
  {
    "country": "BD",
    "cities": [
      "বরগুনা",
      "বরিশাল",
      "ভোলা",
      "ঝালকাঠি",
      "পটুয়াখালী",
      "পিরোজপুর",
      "বান্দরবান",
      "ব্রাহ্মণবাড়ীয়া",
      "চাঁদপুর",
      "চট্টগ্রাম",
      "কুমিল্লা",
      "কক্সবাজার",
      "ফেনী",
      "খাগড়াছড়ি",
      "লক্ষীপুর",
      "নোয়াখালী",
      "রাঙ্গামাটি",
      "ঢাকা",
      "ফরিদপুর",
      "গাজীপুর",
      "গোপালগঞ্জ",
      "জামালপুর",
      "কিশোরগঞ্জ",
      "মাদারীপুর",
      "মানিকগঞ্জ",
      "মুন্সীগঞ্জ",
      "ময়মনসিংহ",
      "নারায়ণগঞ্জ",
      "নরসিংদী",
      "নেত্রকোনা",
      "রাজবাড়ী",
      "শরীয়তপুর",
      "শেরপুর",
      "টাঙ্গাইল",
      "বাগেরহাট",
      "চুয়াডাঙ্গা",
      "যশোর",
      "ঝিনাইদহ",
      "খুলনা",
      "কুষ্টিয়া",
      "মাগুরা",
      "মেহেরপুর",
      "নড়াইল",
      "সাতক্ষিরা",
      "বগুড়া",
      "জয়পুরহাট",
      "নওগাঁ",
      "নাটোর",
      "নওয়াবগঞ্জ",
      "পাবনা",
      "রাজশাহী",
      "সিরাজগঞ্জ",
      "দিনাজপুর",
      "গাইবান্ধা",
      "কুড়িগ্রাম",
      "লালমনিরহাট",
      "নীলফামারী",
      "পঞ্চগড়",
      "রংপুর",
      "ঠাকুরগাঁ",
      "হবিগঞ্জ",
      "মৌলভীবাজার",
      "সুনামগঞ্জ",
      "সিলেট"
    ]
  },
  {
    "country": "PK",
    "cities": [
      "Azad Kashmir",
      "Bahawalpur",
      "Bannu",
      "Dera Ghazi Khan",
      "Dera Ismail Khan",
      "Faisalabad",
      "F.A.T.A.",
      "Gujranwala",
      "Hazara",
      "Hyderabad",
      "Islamabad",
      "Kalat",
      "Karachi",
      "Kohat",
      "Lahore",
      "Larkana",
      "Makran",
      "Malakand",
      "Mardan",
      "Mirpur Khas",
      "Multan",
      "Nasirabad",
      "Northern Areas",
      "Peshawar",
      "Quetta",
      "Rawalpindi",
      "Sargodha",
      "Sahiwal",
      "Sibi",
      "Sukkur",
      "Zhob"
    ]
  },
  {
    "country": "NG",
    "cities": [
      "Abia",
      "Abuja",
      "Adamawa",
      "Akwa Ibom",
      "Anambra",
      "Bauchi",
      "Bayelsa",
      "Benue",
      "Borno",
      "Cross River",
      "Delta",
      "Ebonyi",
      "Edo",
      "Ekiti",
      "Enugu",
      "Gombe",
      "Imo",
      "Jigawa",
      "Kaduna",
      "Kano",
      "Katsina",
      "Kebbi",
      "Kogi",
      "Kwara",
      "Lagos",
      "Nasarawa",
      "Niger",
      "Ogun",
      "Ondo",
      "Osun",
      "Oyo",
      "Plateau",
      "Rivers",
      "Sokoto",
      "Taraba",
      "Yobe",
      "Zamfara"
    ]
  },
  {
    "country": "JP",
    "cities": [
      "愛知県",
      "秋田県",
      "青森県",
      "千葉県",
      "愛媛県",
      "福井県",
      "福岡県",
      "福島県",
      "岐阜県",
      "群馬県",
      "広島県",
      "北海道",
      "兵庫県",
      "茨城県",
      "石川県",
      "岩手県",
      "香川県",
      "鹿児島県",
      "神奈川県",
      "高知県",
      "熊本県",
      "京都府",
      "三重県",
      "宮城県",
      "宮崎県",
      "長野県",
      "長崎県",
      "奈良県",
      "新潟県",
      "大分県",
      "岡山県",
      "沖縄県",
      "大阪府",
      "佐賀県",
      "埼玉県",
      "滋賀県",
      "島根県",
      "静岡県",
      "栃木県",
      "徳島県",
      "東京都",
      "鳥取県",
      "富山県",
      "和歌山県",
      "山形県",
      "山口県",
      "山梨県"
    ]
  },
  {
    "country": "AT",
    "cities": [
      "Burgenland",
      "Kärnten",
      "Niederösterreich",
      "Oberösterreich",
      "Salzburg",
      "Steiermark",
      "Tirol",
      "Vorarlberg",
      "Wien"
    ]
  },
  {
    "country": "BR",
    "cities": [
      "Acre",
      "Alagoas",
      "Amapá",
      "Amazonas",
      "Bahia",
      "Ceará",
      "Distrito Federal",
      "Espírito Santo",
      "Goiás",
      "Maranhão",
      "Mato Grosso",
      "Mato Grosso do Sul",
      "Minas Gerais",
      "Pará",
      "Paraíba",
      "Paraná",
      "Pernambuco",
      "Piauí",
      "Rio de Janeiro",
      "Rio Grande do Norte",
      "Rio Grande do Sul",
      "Rondônia",
      "Roraima",
      "Santa Catarina",
      "São Paulo",
      "Sergipe",
      "Tocantins"
    ]
  },
  {
    "country": "PH",
    "cities": [
      "Abra",
      "Agusan del Norte",
      "Agusan del Sur",
      "Aklan",
      "Albay",
      "Antique",
      "Apayao",
      "Aurora",
      "Basilan",
      "Bataan",
      "Batanes",
      "Batangas",
      "Benguet",
      "Biliran",
      "Bohol",
      "Bukidnon",
      "Bulacan",
      "Cagayan",
      "Camarines Norte",
      "Camarines Sur",
      "Camiguin",
      "Capiz",
      "Catanduanes",
      "Cavite",
      "Cebu",
      "Compostela Valley",
      "Cotabato",
      "Davao del Norte",
      "Davao del Sur",
      "Davao Occidental",
      "Davao Oriental",
      "Dinagat Islands",
      "Eastern Samar",
      "Guimaras",
      "Ifugao",
      "Ilocos Norte",
      "Ilocos Sur",
      "Iloilo",
      "Isabela",
      "Kalinga",
      "La Union",
      "Laguna",
      "Lanao del Norte",
      "Lanao del Sur",
      "Leyte",
      "Maguindanao",
      "Marinduque",
      "Masbate",
      "Misamis Occidental",
      "Misamis Oriental",
      "Mountain Province",
      "Negros Occidental",
      "Negros Oriental",
      "Northern Samar",
      "Nueva Ecija",
      "Nueva Vizcaya",
      "Occidental Mindoro",
      "Oriental Mindoro",
      "Palawan",
      "Pampanga",
      "Pangasinan",
      "Quezon",
      "Quirino",
      "Rizal",
      "Romblon",
      "Samar",
      "Sarangani",
      "Siquijor",
      "Sorsogon",
      "South Cotabato",
      "Southern Leyte",
      "Sultan Kudarat",
      "Sulu",
      "Surigao del Norte",
      "Surigao del Sur",
      "Tarlac",
      "Tawi-Tawi",
      "Zambales",
      "Zamboanga del Norte",
      "Zamboanga del Sur",
      "Zamboanga Sibugay",
      "Metro Manila"
    ]
  },
  {
    "country": "VN",
    "cities": [
      "Hà Nội",
      "Hà Giang",
      "Cao Bằng",
      "Bắc Kạn",
      "Tuyên Quang",
      "Lào Cai",
      "Điện Biên",
      "Lai Châu",
      "Sơn La",
      "Yên Bái",
      "Hòa Bình",
      "Thái Nguyên",
      "Lạng Sơn",
      "Quảng Ninh",
      "Bắc Giang",
      "Phú Thọ",
      "Vĩnh Phúc",
      "Bắc Ninh",
      "Hải Dương",
      "Hải Phòng",
      "Hưng Yên",
      "Thái Bình",
      "Hà Nam",
      "Nam Định",
      "Ninh Bình",
      "Thanh Hóa",
      "Nghệ An",
      "Hà Tĩnh",
      "Quảng Bình",
      "Quảng Trị",
      "Thừa Thiên–Huế",
      "Đà Nẵng",
      "Quảng Nam",
      "Quảng Ngãi",
      "Bình Định",
      "Phú Yên",
      "Khánh Hòa",
      "Ninh Thuận",
      "Bình Thuận",
      "Kon Tum",
      "Gia Lai",
      "Đắk Lắk",
      "Đắk Nông",
      "Lâm Đồng",
      "Bình Phước",
      "Tây Ninh",
      "Bình Dương",
      "Đồng Nai",
      "Bà Rịa–Vũng Tàu",
      "Thành phố Hồ Chí Minh",
      "Long An",
      "Tiền Giang",
      "Bến Tre",
      "Trà Vinh",
      "Vĩnh Long",
      "Đồng Tháp",
      "An Giang",
      "Kiên Giang",
      "Cần Thơ",
      "Hậu Giang",
      "Sóc Trăng",
      "Bạc Liêu",
      "Cà Mau"
    ]
  },
  {
    "country": "CR",
    "cities": [
      "San José",
      "Alajuela",
      "Cartago",
      "Heredia",
      "Guanacaste",
      "Puntarenas",
      "Limón"
    ]
  },
  {
    "country": "NZ",
    "cities": [
      "Auckland",
      "New Plymouth",
      "Hawke's Bay",
      "Wellington",
      "Nelson",
      "Marlborough",
      "Westland",
      "Canterbury",
      "Otago",
      "Southland"
    ]
  }
];

List<DocumentSnapshot> documentSnapshots = [];
bool isLastItem = false;
bool isLastTradeRequest = false;
DocumentSnapshot? lastTradeSnapshot;
